### PR TITLE
Add libprotobuf-dev dependency

### PR DESCRIPTION
**Pull request by lanzani**
Add missing dependency.

### CODE REVIEW

**Comment by PINTO0309** [comment]
Thanks!

**Comment by lanzani** [comment]
You're welcome! Thank you for your work! I'm going to this process right now, but I'm encountering problems during the build.
I will let you know if I solve something.

Btw, my goal is to achieve the following: mediapipe 0.any.any for python 3.8 (or higher) on Jetson Nano. Have you tried this before?

**Comment by PINTO0309** [comment]
I have not tried it because the internal specification of MediaPipe has changed so much and the internal specification is so complex that porting to a GPU is very difficult.

**Comment by lanzani** [comment]
Yeah, it is quite complex unfortunately :)

**Comment by PINTO0309** [comment]
As a practical measure, I am using TensorRT via ONNX. All MediaPipe models are converted and committed.

https://github.com/PINTO0309/PINTO_model_zoo

**Comment by PINTO0309** [comment]
An example.
https://github.com/PINTO0309/hand_landmark

**Comment by lanzani** [comment]
Thank you very much!

From what you know, tensorflow and opencv are both build dependencies for mediapipe?

**Pull request merged**
